apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-http
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: {{ .Values.nginx.service.clusterIP }}
  ports:
    - port: 80
      name: http-tcp
      protocol: TCP
      targetPort: 80
    - port: 80
      name: http-udp
      protocol: UDP
      targetPort: 80
    - port: 443
      name: https-tcp
      protocol: TCP
      targetPort: 443
    - port: 443
      name: https-udp
      protocol: UDP
      targetPort: 443
  externalIPs:
{{- toYaml .Values.nginx.service.externalIPs | nindent 4 }}
  selector:
    name: {{ .Release.Name }}

