apiVersion: v2
name: zunivers-ninja
description: Automated advice tool for the ZUnivers card game (not affiliated)
type: application
version: 1.0.6
appVersion: "latest"
dependencies:
  - name: neo4j
    alias: database
    version: 5.3
    repository: https://helm.neo4j.com/neo4j
