version: 1.6.2

requests:
  cpu: 100m
  memory: 500Mi
limits:
  cpu: 200m
  memory: 1000Mi

ingress:
  className: traefik

database:
  uri: bolt://localhost:7687
  username: neo4j
  password: changeme

toolkit:
  discordTags: Alex'Presso#5480 #Comma separated
  runAutomatedTasks: false

zunivers:
  apiBaseUrl: zunivers-api.zerator.com
  frontBaseUrl: zunivers.zerator.com

webhookUrl: #insert your own (facultative)

github:
  pat: #Use your own
