version: 1.6.2

requests:
  cpu: 100m
  memory: 500Mi
limits:
  cpu: 200m
  memory: 1000Mi

ingress:
  enabled: false
  className: traefik

neo4j:
  core:
    numberOfServers: 1
  name: zuninja-db
  neo4jPassword: changeme

toolkit:
  discordTags: Alex'Presso#5480 #Comma separated
  runAutomatedTasks: false

zunivers:
  apiBaseUrl: zunivers-api.zerator.com
  frontBaseUrl: zunivers.zerator.com

webhookUrl: #insert your own (facultative)

github:
  pat: #Use your own
