apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  labels:
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
stringData:
  wg0.conf.template: |
    [Interface]
    Address = {{ .Values.wireguard.config.address }}
    PrivateKey = {{ .Values.wireguard.config.privateKey }}
    ListenPort = {{ .Values.wireguard.config.listenPort }}
    {{- if .Values.wireguard.config.disableTable }}
    Table = off
    {{- end}}
    {{- if .Values.wireguard.config.dns }}
    DNS = {{ .Values.wireguard.config.dns }}
    {{- end }}
    MTU = {{ .Values.wireguard.config.mtu }}

    PostUp = iptables -A FORWARD -i %i -j ACCEPT
    PostUp = iptables -A FORWARD -o %i -j ACCEPT
    PostUp = iptables -t nat -A POSTROUTING -o ENI -j MASQUERADE
    {{- range .Values.wireguard.config.additionalPostUp }}
    PostUp = {{ . }}
    {{- end}}

    {{- range .Values.wireguard.config.additionalPostDown }}
    PostDown = {{ . }}
    {{- end }}
    PostDown = iptables -D FORWARD -i %i -j ACCEPT
    PostDown = iptables -D FORWARD -o %i -j ACCEPT
    PostDown = iptables -t nat -D POSTROUTING -o ENI -j MASQUERADE

    {{- range .Values.wireguard.peers }}
    [Peer]
    PublicKey = {{ .publicKey }}
    AllowedIPs = {{ .allowedIPs }}
    PersistentKeepAlive = {{ .keepAlive }}
    {{- if .presharedKey }}
    PresharedKey = {{ .presharedKey }}
    {{- end }}
    {{- end }}
