apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  labels:
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
stringData:
  wg0.conf.template: |
    [Interface]
    Address = {{ .Values.wireguard.config.address }}
    PrivateKey = {{ .Values.wireguard.config.privateKey }}
    ListenPort = {{ .Values.wireguard.config.listenPort }}
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ENI -j MASQUERADE
    PostUp = sysctl -w -q net.ipv4.ip_forward=1
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ENI -j MASQUERADE
    PostDown = sysctl -w -q net.ipv4.ip_forward=0
    {{- if .Values.wireguard.config.dns }}
    DNS = {{ .Values.wireguard.config.dns }}
    {{- end }}
    MTU = {{ .Values.wireguard.config.mtu }}

    {{- range .Values.wireguard.peers }}
    [Peer]
    PublicKey = {{ .publicKey }}
    AllowedIPs = {{ .allowedIPs }}
    PersistentKeepAlive = {{ .keepAlive }}
    {{- if .presharedKey }}
    PresharedKey = {{ .presharedKey }}
    {{- end }}
    {{- end }}
