timezone: "America/Chicago"

hostNetwork: false #Highly recommended if enabling DHCP
image:
  tag: "2025.04.0"
webinterface:
  password: #Set your own
  port: 8080 #used as hostPort or servicePort depending on above boolean :)
  service:
    enable: true
    type: LoadBalancer

dns:
  adlist:
    - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    - https://blocklistproject.github.io/Lists/phishing.txt
    - https://blocklistproject.github.io/Lists/redirect.txt
    - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
    #Prevents local iOS devices from enforcing Apple's DoH :
    - https://raw.githubusercontent.com/oneoffdallas/dohservers/master/list.txt
    - https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-domains.txt
  whitelist: []
  blacklist: []

  cacheSize: 10000

  # DNSSEC
  # - Requires cacheSize >= 100
  # - Can cause issues on custom local domains if not using pihole as DHCP
  # - No value to enable if using CloudFlare DOH (config bellow) :
  #   - "DNSSEC" is inherent of DoH
  #   - No one is going to alter DNS replies between the containers inside your pod...
  dnsSec: "true"

  customDnsEntries:
    cname: []
#      - cname=CNAME record,DNS record
#      - cname.foo.bar,foo.bar
    a: []
#      - 192.168.1.202 domain.local

  #Overridden by CloudFlare DoH if enabled
  servers:
    - 1.1.1.1
    - 1.0.0.1
#    - 2606:4700:4700::1111
#    - 2606:4700:4700::1001
#    - 127.0.0.1
  service:
    enable: true
    type: LoadBalancer
    port: 53

dhcp:
  enable: false
  ip:
    router: 192.168.1.1
    rangeStart: 192.168.1.201
    rangeEnd: 192.168.1.251
    staticIps: []
#      - MAC_ADDRESS,IP_ADDRESS,HOSTNAME
#      - 00:00:00:00:00:00,192.168.1.202,AwesomeName
  service:
    enable: false
    type: LoadBalancer
    port: 67

ntp:
  enable: true
  syncServer: pool.ntp.org
  service:
    enable: true
    type: LoadBalancer
    port: 123

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi

volume:
  annotations:
  storageClass: ""
  size: 500Mi

ingress:
  enable: true
  host: pihole.local
  tls: true
  className: traefik
  annotations:
#    traefik.ingress.kubernetes.io/router.tls: "true"
#    cert-manager.io/cluster-issuer: local-ca-issuer


cloudflareDoh:
  enable: true
  image:
    tag: "2025.2.1"
  upstreams:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
#    - https://[2606:4700:4700::1111]/dns-query
#    - https://[2606:4700:4700::1001]/dns-query
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 128Mi
