timezone: "America/Chicago"
webpassword: #Set your own

#Overridden if enabling CloudFlare DoH
dns:
  - 1.1.1.1
  - 1.0.0.1

service:
  dns:
    enable: true
    type: NodePort
    port: 53
  dhcp:
    enable: true
    type: NodePort
    port: 67
  http:
    enable: true
    type: NodePort
    httpPort: 80
    httpsPort: 443

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

volume:
  annotations:
  storageClass: ""
  size: 1Gi

cloudflareDoh:
  enable: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  upstreams:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
#    - https://[2606:4700:4700::1111]/dns-query
#    - https://[2606:4700:4700::1001]/dns-query