apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.json: |
    {
      "frontBaseUrl": "{{ .Values.config.zunivers.front_base_url }}",
      "cdnBaseUrl": "{{ .Values.config.zunivers.cdn_base_url }}",
      "api": {
        "baseurl": "{{ .Values.config.zunivers.api_base_url }}",
        "timeout": 10,
        "rulesettype": "{{ .Values.config.zunivers.ruleset_type }}"
      },
      "emojis": {{ toJson .Values.config.emojis }},
      "webhooks": {{ toJson .Values.config.webhooks }},
      "events": {{ toJson .Values.config.events }}
    }
