apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      containers:
        - name: application
          image: golang
          imagePullPolicy: IfNotPresent
          env:
            - name: "GOPROXY"
              value: direct
          resources:
            requests:
              cpu: 100m
              memory: 500M
          volumeMounts:
            - name: {{ .Release.Name }}-config-vol
              mountPath: /go/config.json
              subPath: config.json
            - name: timezone
              mountPath: /etc/localtime
              subPath: Europe/Paris
              readOnly: true
      volumes:
        - name: {{ .Release.Name }}-config-vol
          configMap:
            name: {{ .Release.Name }}-config
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo
