apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  application.yml: |-
    spring.neo4j:
      uri: "bolt://${DB_HOST}:7687"
      authentication:
        username: neo4j
        password: ${NEO4J_PASSWORD}

    toolkit:
      discordTags: {{ required "discordTags value is required." .Values.config.discordTags }}
      runAutomatedTasks: {{ default false .Values.config.runAutomatedTasks }}

    zunivers:
      apiBaseUrl: {{ .Values.config.zunivers.apiBaseUrl }}
      frontBaseUrl: {{ .Values.config.zunivers.frontBaseUrl }}
      gameMode: {{ .Values.config.zunivers.gameMode }}

    webhookUrl: ${WEBHOOK_URL}

    logging:
      level:
        me.alexpresso.zuninja: INFO
