apiVersion: apps/v1
kind: Deployment
metadata:
  name: zunivers-ninja
spec:
  selector:
    matchLabels:
      name: zunivers-ninja
  template:
    metadata:
      labels:
        name: zunivers-ninja
    spec:
      containers:
        - name: zuninja-db
          image: neo4j
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ default "100m" .Values.requests.cpu }}
              memory: {{ default "500Mi" .Values.requests.memory }}
            limits:
              cpu: {{ default "200m" .Values.limits.cpu }}
              memory: {{ default "1000Mi" .Values.limits.memory }}
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
              subPath: Europe/Paris
              readOnly: true
          env:
            - name: NEO4J_ACCEPT_LICENCE_AGREEMENT
              value: yes
            - name:
      volumes:
        - name: zuninja-config-vol
          configMap:
            name: zuninja-config
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo
