apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-app
          image: ghcr.io/alexpresso/zunivers-ninja:1.8.6
          imagePullPolicy: IfNotPresent
          resources:
{{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: {{ .Release.Name }}-config-vol
              mountPath: /config/application.yml
              subPath: application.yml
            - name: timezone
              mountPath: /etc/localtime
              subPath: Europe/Paris
              readOnly: true
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: {{ $.Release.Name }}
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  key: pat
                  name: zuninja-secrets
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: zuninja-secrets
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  key: webhookUrl
                  name: zuninja-secrets
      volumes:
        - name: {{ .Release.Name }}-config-vol
          configMap:
            name: {{ .Release.Name }}-config
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo
