apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-app
          image: ghcr.io/alexpresso/zunivers-ninja:1.20.0
          imagePullPolicy: IfNotPresent

          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2

          resources:
{{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: {{ .Release.Name }}-config-vol
              mountPath: /app/config/application.yml
              subPath: application.yml
            - name: timezone
              mountPath: /etc/localtime
              subPath: Europe/Paris
              readOnly: true
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: {{ .Release.Name }}
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}-secrets
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  key: webhookUrl
                  name: {{ .Release.Name }}-secrets
            - name: JAVA_OPTS
              value: {{ .Values.java.opts }}
      volumes:
        - name: {{ .Release.Name }}-config-vol
          configMap:
            name: {{ .Release.Name }}-config
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo
