apiVersion: v1
kind: Ingress
metadata:
  name: zuninja-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              resource:
                name: zunivers-ninja