apiVersion: v1
kind: Secret
metadata:
  name: zuninja-secrets
  labels:
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
data:
  username: {{ default "" .Values.database.username | quote }}
  password: {{ default "" .Values.database.password | quote }}
  pat: {{ default "" .Values.github.pat | quote }}