apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
data:
  password: {{ default "" .Values.database.neo4j.password | b64enc | quote }}
  webhookUrl: {{ default "" .Values.config.webhookUrl | b64enc | quote }}
