apiVersion: v1
kind: Service
metadata:
  name: zuninja-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    name: zunivers-ninja
