apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lists
data:
  adlists.list: |
{{- range .Values.dns.adlist }}
    {{ . }}
{{- end }}

  whitelist.txt: |
{{- range .Values.dns.whitelist }}
    {{ . }}
{{- end }}

  blacklist.txt: |
{{- range .Values.dns.blacklist }}
    {{ . }}
{{- end }}

  1-additional.conf: |
{{- range .Values.dns.additionalDnsmasq }}
    {{ . }}
{{- end }}