apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      {{ if .Values.service.dhcp.enable }}
      hostNetwork: true
      {{ end }}
      volumes:
        - name: {{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: ghcr.io/pi-hole/pihole
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/pihole
              name: {{ .Release.Name }}
            - mountPath: /etc/dsnmasq.d
              name: {{ .Release.Name }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND_SERVICE
                - NET_RAW
                - NET_ADMIN
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 53
            - containerPort: 67
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: WEB_PORT
              value: "8080"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: webpassword
                  name: {{ .Release.Name }}-secrets
            - name: PIHOLE_DNS_
              {{ if .Values.cloudflareDoh.enable }}
              value: "127.0.0.1#5053"
              {{ else }}
              value: {{ join "," .Values.dns }}
              {{ end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              port: 8080
              path: &probe-uri /admin
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: *probe-uri
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 4

      {{ if .Values.cloudflareDoh.enable }}
        - name: {{ .Release.Name }}-cloudflared
          image: cloudflare/cloudflared
          imagePullPolicy: IfNotPresent
          args:
            - proxy-dns
          env:
            - name: TUNNEL_DNS_ADDRESS
              value: "0.0.0.0"
            - name: TUNNEL_DNS_PORT
              value: "5053"
            - name: TUNNEL_DNS_UPSTREAM
              value: {{ join "," .Values.cloudflareDoh.upstreams }}
          resources:
{{- toYaml .Values.cloudflareDoh.resources | nindent 12 }}
          ports:
            - containerPort: 5053
      {{ end }}