apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: ghcr.io/pi-hole/pihole
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc
              name: {{ .Release.Name }}
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 53
            - containerPort: 67
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: webpassword
                  name: {{ .Release.Name }}-secrets
            - name: PIHOLE_DNS_
              {{if .Values.cloudflareDoh.enable }}
              value: "127.0.0.1#5053"
              {{-else}}
              value: {{ join "," .Values.dns }}
              {{-end}}
          resources:
{{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              port: 80
              path: &probe-uri /admin
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: *probe-uri
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2

      {{ if .Values.cloudflareDoh.enabled }}
        - name: {{ .Release.Name }}-cloudflared
          image: cloudflare/cloudflared
          imagePullPolicy: IfNotPresent
          args:
            - proxy-dns
          env:
            - name: TUNNEL_METRICS
              value: &broadcast "0.0.0.0"
            - name: TUNNEL_DNS_ADDRESS
              value: *broadcast
            - name: TUNNEL_DNS_PORT
              value: "5053"
            - name: TUNNEL_DNS_UPSTREAM
              value: {{ join "," .Values.cloudflareDoh.upstreams }}
          resources:
{{- toYaml .Values.cloudflareDoh.resources | nindent 12 }}
          ports:
            - containerPort: 5053
      {{-end}}7