apiVersion: apps/v1
{{ if .Values.hostNetwork }}
kind: DaemonSet
{{ else }}
kind: Deployment
{{ end }}
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  {{ if .Values.hostNetwork }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  {{ end }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      {{ if .Values.hostNetwork }}
      hostNetwork: true
      {{ end }}
      volumes:
        - name: {{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
        - name: {{ .Release.Name }}-lists
          configMap:
            name: {{ .Release.Name }}-lists
            defaultMode: 420

      containers:
        - name: {{ .Release.Name }}
          image: ghcr.io/pi-hole/pihole:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/pihole
              name: {{ .Release.Name }}
            - mountPath: /etc/pihole/adlists.list
              name: {{ .Release.Name }}-lists
              subPath: adlists.list
            - mountPath: /etc/pihole/whitelist.txt
              name: {{ .Release.Name }}-lists
              subPath: whitelist.txt
            - mountPath: /etc/pihole/blacklist.txt
              name: {{ .Release.Name }}-lists
              subPath: blacklist.txt
            - mountPath: /etc/dnsmasq.d/1-additional.conf
              name: {{ .Release.Name }}-lists
              subPath: 1-additional.conf
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND_SERVICE
                - NET_RAW
                - SYS_NICE
                - SYS_TIME
                - CHOWN
          ports:
            {{ if .Values.hostNetwork }}
            - containerPort: {{ .Values.webinterface.port }}
              protocol: TCP
            {{ else }}
            - containerPort: 8080
              protocol: TCP
            {{ end }}
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 67
              protocol: UDP
            - containerPort: 123
              protocol: UDP
          env:
            - name: FTLCONF_webserver_port
              value: "8080"
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  key: webpassword
                  name: {{ .Release.Name }}-secrets
            - name: FTLCONF_dns_upstreams
              {{ if .Values.cloudflareDoh.enable }}
              value: "127.0.0.1#5053;::1#5053"
              {{ else }}
              value: {{ join ";" .Values.dns.servers }}
              {{ end }}
            - name: FTLCONF_dns_cache_size
              value: {{ .Values.dns.cacheSize | quote }}
            - name: FTLCONF_dns_dnssec
              value: {{ .Values.dns.dnsSec | quote }}
            - name: FTLCONF_dns_hosts
              value: {{ join ";" .Values.dns.customDnsEntries.a | quote }}
            - name: FTLCONF_dns_cnameRecords
              value: {{ join ";" .Values.dns.customDnsEntries.cname | quote }}
            {{ if gt (len .Values.dns.additionalDnsmasq) 0 }}
            - name: FTLCONF_misc_etc_dnsmasq_d
              value: "true"
            {{ end }}
            {{ if .Values.dhcp.enable }}
            - name: FTLCONF_dhcp_active
              value: "true"
            - name: FTLCONF_dhcp_start
              value: {{ .Values.dhcp.ip.rangeStart | quote }}
            - name: FTLCONF_dhcp_end
              value: {{ .Values.dhcp.ip.rangeEnd | quote }}
            - name: FTLCONF_dhcp_router
              value: {{ .Values.dhcp.ip.router | quote }}
            - name: FTLCONF_dhcp_hosts
              value: {{ join ";" .Values.dhcp.ip.staticIps | quote }}
            {{ end }}
            {{ if .Values.ntp.enable }}
            - name: FTLCONF_ntp_sync_server
              value: {{ .Values.ntp.syncServer }}
            {{ end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              {{ if .Values.hostNetwork }}
              port: {{ .Values.webinterface.port }}
              {{ else }}
              port: 8080
              {{ end }}
              path: &probe-uri /admin
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              {{ if .Values.hostNetwork }}
              port: {{ .Values.webinterface.port }}
              {{ else }}
              port: 8080
              {{ end }}
              path: *probe-uri
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5

      {{ if .Values.cloudflareDoh.enable }}
        - name: {{ .Release.Name }}-cloudflared
          image: cloudflare/cloudflared:{{ .Values.cloudflareDoh.image.tag }}
          imagePullPolicy: IfNotPresent
          args:
            - proxy-dns
          env:
            - name: TUNNEL_DNS_ADDRESS
              value: "0.0.0.0"
            - name: TUNNEL_DNS_PORT
              value: "5053"
            - name: TUNNEL_DNS_UPSTREAM
              value: {{ join "," .Values.cloudflareDoh.upstreams }}
          resources:
{{- toYaml .Values.cloudflareDoh.resources | nindent 12 }}
          ports:
            - containerPort: 5053
      {{ end }}
