apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      {{ if .Values.hostNetwork }}
      hostNetwork: true
      {{ end }}
      volumes:
        - name: {{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
        - name: {{ .Release.Name }}-lists
          configMap:
            name: {{ .Release.Name }}-lists
            defaultMode: 420

      containers:
        - name: {{ .Release.Name }}
          image: ghcr.io/pi-hole/pihole
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/pihole
              name: {{ .Release.Name }}
            - mountPath: /etc/pihole/adlists.list
              name: {{ .Release.Name }}-lists
              subPath: adlists.list
            - mountPath: /etc/pihole/whitelist.txt
              name: {{ .Release.Name }}-lists
              subPath: whitelist.txt
            - mountPath: /etc/pihole/blacklist.txt
              name: {{ .Release.Name }}-lists
              subPath: blacklist.txt
            - mountPath: /etc/dnsmasq.d/02-custom.conf
              name: {{ .Release.Name }}-lists
              subPath: 02-custom.conf
            {{ if .Values.dhcp.enable }}
            - mountPath: /etc/dnsmasq.d/04-pihole-static-dhcp.conf
              name: {{ .Release.Name }}-lists
              subPath: pihole-static-dhcp.conf
            {{ end }}
            - mountPath: /etc/dnsmasq.d/05-pihole-custom-cname.conf
              name: {{ .Release.Name }}-lists
              subPath: 05-pihole-custom-cname.conf
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND_SERVICE
                - NET_RAW
                - SYS_NICE
                - CHOWN
          ports:
            {{ if .Values.hostNetwork }}
            - containerPort: {{ .Values.webinterface.port }}
              protocol: TCP
            {{ else }}
            - containerPort: 8080
              protocol: TCP
            {{ end }}
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 67
              protocol: UDP
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: WEB_PORT
              value: "8080"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: webpassword
                  name: {{ .Release.Name }}-secrets
            - name: PIHOLE_DNS_
              {{ if .Values.cloudflareDoh.enable }}
              value: "127.0.0.1#5053"
              {{ else }}
              value: {{ join ";" .Values.dns.servers }}
              {{ end }}
            - name: CUSTOM_CACHE_SIZE
              value: {{ .Values.dns.cacheSize | quote }}
            {{ if .Values.dhcp.enable }}
            - name: DHCP_ACTIVE
              value: "true"
            - name: DHCP_START
              value: {{ .Values.dhcp.ip.rangeStart | quote }}
            - name: DHCP_END
              value: {{ .Values.dhcp.ip.rangeEnd | quote }}
            - name: DHCP_ROUTER
              value: {{ .Values.dhcp.ip.router | quote }}
            {{ end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              {{ if .Values.hostNetwork }}
              port: {{ .Values.webinterface.port }}
              {{ else }}
              port: 8080
              {{ end }}
              path: &probe-uri /admin
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 2
          readinessProbe:
            httpGet:
              {{ if .Values.hostNetwork }}
              port: {{ .Values.webinterface.port }}
              {{ else }}
              port: 8080
              {{ end }}
              path: *probe-uri
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 4

      {{ if .Values.cloudflareDoh.enable }}
        - name: {{ .Release.Name }}-cloudflared
          image: cloudflare/cloudflared
          imagePullPolicy: IfNotPresent
          args:
            - proxy-dns
          env:
            - name: TUNNEL_DNS_ADDRESS
              value: "0.0.0.0"
            - name: TUNNEL_DNS_PORT
              value: "5053"
            - name: TUNNEL_DNS_UPSTREAM
              value: {{ join "," .Values.cloudflareDoh.upstreams }}
          resources:
{{- toYaml .Values.cloudflareDoh.resources | nindent 12 }}
          ports:
            - containerPort: 5053
      {{ end }}
