{{ if and .Values.service.dns.enable (not .Values.service.hostNetwork) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-dns
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.dns.type }}
  ports:
    - port: {{ .Values.service.dns.port }}
      protocol: UDP
      targetPort: 53
      name: dns-udp
    - port: {{ .Values.service.dns.port }}
      protocol: TCP
      targetPort: 53
      name: dns-tcp
  selector:
    name: {{ .Release.Name }}

{{ end }}
