{{ if and .Values.service.dhcp.enable (not .Values.service.hostNetwork) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-dhcp
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.dhcp.type }}
  ports:
    - port: {{ .Values.service.dhcp.port }}
      targetPort: 67
      name: dhcp
  selector:
    name: {{ .Release.Name }}

{{ end }}
