apiVersion: v2
description: Installs an NGinX SNI Proxy in kubernetes
type: application
home: https://github.com/AlexPresso/helm.alexpresso.me/tree/main/charts/nginx-sni-proxy
name: nginx-sni-proxy
appVersion: "latest"
version: 1.0.1
sources:
  - https://github.com/AlexPresso/helm.alexpresso.me/tree/main/charts/nginx-sni-proxy
  - https://nginx.org/
  - https://hub.docker.com/_/nginx
icon: https://nginx.org/img/nginx_logo_dark.png
maintainers:
  - name: AlexPresso
