volume:
  annotations: []
  storage: 50Mi
  storageClass: {}

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

service:
  enable: true
  type: ClusterIP
  externalTrafficPolicy: Local
  port: 80

config:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Chicago"
  SERVERPORT: "51820"
  SERVERURL: "<pihole.example.com>"
  PEERS: "5"
  PEERDNS: "10.43.0.30"
  ALLOWEDIPS: "0.0.0.0/0, ::/0"
  INTERNAL_SUBNET: "10.13.13.0"
