apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-searxng
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-searxng
        - name: {{ .Release.Name }}-settings
          configMap:
            name: {{ .Release.Name }}-settings

      containers:
        - name: {{ .Release.Name }}
          image: searxng/searxng
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/searxng
              name: {{ .Release.Name }}-searxng
            - mountPath: /etc/searxng/settings.yml
              name: {{ .Release.Name }}-settings
              subPath: settings.yml
          securityContext:
            capabilities:
              add:
                - SETGID
                - SETUID
                - CHOWN
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SEARXNG_BIND_ADDRESS
              value: "0.0.0.0"
            - name: SEARXNG_PORT
              value: "8080"
            - name: SEARXNG_SECRET
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: {{ .Release.Name }}-secrets
          resources:
{{- toYaml .Values.searxng.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              port: &probe-port 8080
              path: &probe-uri /healthz
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: *probe-port
              path: *probe-uri
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 4
