{{ if .Values.searxng.ingress.enable }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  {{ if .Values.searxng.ingress.annotations }}
  annotations:
{{- toYaml .Values.searxng.ingress.annotations | nindent 4 }}
  {{ end }}
spec:
  ingressClassName: {{ .Values.searxng.ingress.className }}
  {{- if .Values.searxng.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.searxng.ingress.host }}
      secretName: {{ .Release.Name }}-cert
  {{- end }}

  rules:
    - host: {{ .Values.searxng.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-svc-http
                port:
                  number: {{ .Values.searxng.service.port }}
{{ end }}
