{{ if .Values.searxng.ingress.enable }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
  {{- if .Values.searxng.ingress.annotations }}
  {{ toYaml .Values.searxng.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.searxng.ingress.tls.enable }}
  tls:
    - hosts:
        - {{ .Values.searxng.ingress.host }}
      secretName: {{ .Values.searxng.ingress.tls.secretName }}
  {{- end }}

  rules:
    - host: {{ .Values.searxng.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-svc-http
                port:
                  number: 80
{{ end }}
