apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
data:
  secretKey: {{ required "Web password is missing" .Values.searxng.settings.server.secret_key | b64enc | quote }}
