{{ if .Values.searxng.service.enable }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-http
  namespace: {{ .Release.Namespace }}
spec:
  externalTrafficPolicy: Local
  type: {{ .Values.searxng.service.type }}
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 443
      name: http
      protocol: TCP
      targetPort: 8080

  selector:
    name: {{ .Release.Name }}

{{ end }}
